### ISSUE TITLE
Мелкие баги

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Android#127]
- [x] кнопка "Оценить" в ворке может залезть на описание (f.e. цикл Expanse)
- [x] описание ворка может оказаться впритык к границам лэйаута (там же)
- [x] по идее, у книги 2 автора (там же), соответственно, отображать надо обоих (если приходят)
- [x] если у похожей книги нет русского названия, отображается пустое место (там же, Firefly)
- [x] если у ворка нет русского названия, место под него остается, но пустое (Firefly)
- [x] автора "Межавторский цикл" отображать не надо (так же, как и Анонимного автора, и Неизвестного автора) (там же)
- [x] FAB при скролле не скрывается и заслоняет контент (там же, классификация, отзывы)
- [x] последние похожие книги вплотную прилегают снизу к границам лэйаута (там же)
- [x] если у издания не указан год выхода, он отображается как 0 (просто не надо показывать) (The Lion Men of Mongo - издания)
- [x] если у издания неизвестно количество страниц, не указывать его (издание "Флэш Гордон")
- [x] если издание только готовится к выходу, отображать предупреждение об этом (там же)
- [x] к релизу убрать предупреждения о неопознанных типах ссылки (либо убирать ссылки, либо отправлять пока в браузер)
- [x] в содержании цикла, если не указан год, выводится null (ничего не выводит) (Тысяча и одна ночь)
- [x] краш при скролле содержания в BetterLinkMovementExtended.java:249 (там же)
- [x] порядок разделов в библио поменять в соответствии с сайтом
- [x] если об авторе толком нет никакой информации и он еще не открыт, описание выглядит очень коряво (автор "Межавторский цикл")
- [x] издания в релизной версии не грузятся (в дебажной норм)
- [x] в списке найденных произведений, в случае отсутствия года, выводится N/A, что не несет никакой смысловой нагрузки
- [x] ShapedImageView & android 9
- [x] ошибка при долгом клике на произведении в библиографии
- [x] пустое название произведения при изменении оценки в случае, если нет русского названия
- [x] блок "Похожие книги" выводится даже если нет похожих - остается только заголовок блока
- [x] при скролле списка оценок в профиле отметка отзыва появляется не в тех item-ах. скорее всего, в onBind не делается очистка значка
- [x] блок "Похожие книги" скроллится очень туго. возможно, проблема в непроставленном `nestedScrollingEnable=false`
- [x] предлагаю выставление оценки ворку перенести в FAB - на соседних вкладках он тоже есть. да и смотреться будет красивее
- [x] в сканере баркода сообщение локализовать (сейчас хардкод `Scan`)
- [x] fab у отзывов автора
- [x] аватарку внутри отзыва заменить на аватарку ворка вместо юзера - иначе смотрится очень странно
- [x] в ленте отзывов, если у отзыва нет голосов, иконку вообще не показывать
- [x] прокидывать сам отзыв на экран отзыва - потенциально опасное решение. можно на каком-нибудь очень длинном отзыве нарваться на ограничения размера Binder'а. но вообще не принципиально, вряд ли такая ситуация случится in the wild
- [x] Цикл не определяется везде, кроме поиска, и считается отдельным произведением
- [x] вырезать спойлеры в ленте отзывов (навскидку не найду, но вчера попался отзыв, который в 3 строках умудрился проспойлерить всю интригу)
- [x] после сохранения классификации надо обновлять классификатор (решается через `startActivityForResult`)
- [x] а если голосов < 0, попробовать ее перевернуть (посмотреть, норм будет смотреться или нет)
- [x] работа deeplinks при наличии в ссылке параметров
- [x] проблему голосования за отзыв новичков по-хорошему надо решать иначе - просто не выводить им вариант минусования (`ResponseOverviewPresenter`)
- [x] еще бы я предложил сортировку (тех же отзывов) тоже переделать на связку fab + bottom-menu, ради единообразия
- [x] плавающие подписи у списка оценок при обновлении
- [ ] поправить везде, где не хватает, отступы по material guidelines (16dp слева-справа, по 8dp вертикальные отступы etc), чтобы контент не выглядел скученно
- [ ] если перейти на экран издания без интернета и кеширования, title неадекватный
- дополняем по мере появления

**Comment by HombreTech** [comment]
Сомневаюсь, что кто-то напишет отзыв более 1МБ. onSavedState ты выпилил, так что в ограничение размера транзакции мы вряд ли упремся.

**Comment by kenrube** [comment]
Я как раз про это - можно, в принципе, удалить этот пункт

**Comment by HombreTech** [comment]
Безумная идея, но может стоит вообще закрывать издание/произведение/etc в случае, если фрагмент Overview выдал ошибку. Не могу придумать ситуацию, когда подобная ошибка в обзоре не сочеталась бы с ошибками остальных вкладок.

**Comment by kenrube** [comment]
Это контринтуитивно - для юзера это будет выглядеть как краш экрана. А если не закрываем - у юзера есть возможность перезагрузить.
К тому же, в авторе (если правильно помню) запрос изданий происходит по другому урлу, так что вполне может случиться ситуация, когда издания загрузятся, а основная информация нет

**Comment by HombreTech** [comment]
@kenrube ну, я и говорю - безумная. :D

**Comment by HombreTech** [comment]
> после сохранения классификации надо обновлять классификатор

Не очень понял о чем здесь речь. Я бы понял еще, если бы наоборот было - после сохранения классификатора, обновлять классификацию. Для меня классификатор - диалог с выбором классификаций, а сама классификация - вкладка у произведения.

**Comment by HombreTech** [comment]
И куда мы столько fab`ов влепим, чтобы сортировку вызывать еще? Сейчас ведь один для добавления отзыва используется. 🤔

**Comment by kenrube** [comment]
А, ну да, тогда не вариант

**Comment by HombreTech** [comment]
Как вариант, сделать а хедере что-нибудь подобное. 
![screenshot_20181130-222037](https://user-images.githubusercontent.com/9828409/49310171-9987ae80-f4ee-11e8-9b94-4a077e03b133.png)

**Comment by kenrube** [comment]
Вьюшку выше списка? Вариант, в принципе. Сейчас просто весьма неочевидные действия надо совершить, чтобы попасть в меню сортировки :)
