### ISSUE TITLE
Проверить и поправить внешний вид экранов при загрузке без сети и кеша

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Android#128]

**Comment by HombreTech** [comment]
![screenshot_20181126-211154](https://user-images.githubusercontent.com/9828409/49033604-b48db200-f1c0-11e8-9490-bcb055d753fc.png)
![screenshot_20181126-211113](https://user-images.githubusercontent.com/9828409/49033606-b48db200-f1c0-11e8-9743-30cb58c0b79e.png)
![screenshot_20181126-211246](https://user-images.githubusercontent.com/9828409/49033607-b5264880-f1c0-11e8-9cc2-23afd946c081.png)
Для информативности. 
О способах решения пока думаю. Из первых идей - возвращать null вместо work/award/edition в случае ошибки и в данном случае устанавливать видимость всех карточек в GONE, добавлять подпись вместо имени/названия с сообщением об ошибке.

**Comment by HombreTech** [comment]
@kenrube и оставить пустые поля с fab, который ведёт к npe?

**Comment by kenrube** [comment]
Fab, соответственно, убирать. По идее, это состояние ничем не отличается от того, когда мы грузили данные без интернета и еще не было кеша. Не удалось - показываем ошибку.

**Comment by HombreTech** [comment]
Понятно. Значит оставляем как есть, за исключением fab.
