### ISSUE TITLE
Персонализировать кеш

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Android#129]
Проблема текущей реализации - в таблице `response` нет поля `userId`. Потенциально это может создавать коллизии с персонализированными запросами (например, оценки в библиографии) для разных юзеров на одном девайсе. Я вижу два решения:
1. Добавить в таблицу поле `user_id` и при запросах учитывать `id` текущего юзера (`-1` для гостя). Можно при каждом вызове `get(url)` и в `dbResponseInterceptor` дергать `PrefGetter.getUser()`, однако, это накладно по времени, поэтому есть смысл завести синглтон с `userId` и инвалидейтить его при логине/разлогине
2. При логине/разлогине стирать из `response` персонализированные запросы. Плохо тем, что при перезаходе старого юзера и отсутствии сети для него уже не будет найдена в базе закешированная персонализированная информация

Лучше эту задачу сделать до первого релиза, иначе потом придется писать миграцию с добавлением нового поля в существующую таблицу

**Comment by HombreTech** [comment]
Решил не строить синглтон, для userId хватит и статики обычной. Присваиваем только при запуске приложения/авторизации, что исключает ошибочные данные.
Впрочем, последнее слово за тобой.

**Comment by kenrube** [comment]
Не-не, все норм, главное, чтобы не читать каждый раз из SP. Присваивать значение достаточно при запуске, инвалидейтить - при событиях логина/разлогина.
