### ISSUE TITLE
Сделать автоперенаправление с сайта в приложение

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Android#138]
Для Android 6+

http://fantlab.ru/blogarticle59250page2#comment415375

**Comment by HombreTech** [comment]
Перенаправление и так работает, что именно нужно сделать?

**Comment by kenrube** [comment]
Сейчас оно работает с подтверждением в виде диалога, можно обойтись без него для Android 6+. Я разберусь с этим вопросом
