### ISSUE TITLE
Travis билд фейлится из-за FOSSA

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Android#142]
```
$ fossa analyze
FATAL Could not parse modules: No modules provided
The command "fossa analyze" exited with 1.
```
Что за `module` - пока неясно. Источник ошибки:
  - https://github.com/fossas/fossa-cli/blob/master/cmd/fossa/cmd/analyze/analyze.go#L42
  - https://github.com/fossas/fossa-cli/blob/master/config/keys.go#L192

**Comment by HombreTech** [comment]
Не актуально?

**Comment by kenrube** [comment]
Актуально, не закрывай. Чтобы не фейлило сборку, в конфиге строка [закомментирована](https://github.com/FantLab/FantLab-Android/blob/master/.travis.yml#L30)

**Comment by kenrube** [comment]
Отключил FOSSA, плохая поддержка gradle ее полностью обесценивает
