### ISSUE TITLE
Добавить изображения на сплеш-скрин

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Android#143]
Есть идея запилить на сплеш вместо скучного синего экрана ретропостеры. См. https://www.jpl.nasa.gov/visions-of-the-future/ - изображения в свободном доступе, смотрятся шикарно. Необязательно зашивать в приложение, можно договориться с @Mazian и добавить на сервер, раз в день заменяя постер на рандомный

**Comment by HombreTech** [comment]
Делал на этом же экране нечто подобное, только для видео-ориентированного приложения.
![2019-03-09 20-52-43 Screenshot](https://user-images.githubusercontent.com/9828409/54075248-2c827280-42ae-11e9-8c00-5896165f32fc.jpg)

**Comment by kenrube** [comment]
Норм 👍 Хотя я подразумевал именно сплеш-скрин, но и на логин тоже можно подобный постер засунуть

**Comment by HombreTech** [comment]
Учитывая размер постеров - неслабые потери памяти будут. Да и, насколько я помню, гугл [рекомендовал ](https://material.io/design/communication/launch-screen.html)использовать сплеш в виде иконки приложения.

**Comment by kenrube** [comment]
Как бы их надо ужать - не надо tiff тянуть, это нецелесообразно
