### ISSUE TITLE
Не обрабатывается ошибка устаревшего токена авторизации

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Android#44]
В любом запросе у нас подставляется авторизационная кука, у которой есть Expire-Date = 1 год. В случае устаревшей куки мы получим ошибку от сервера, которая сейчас не обрабатывается. Необходимо добавить в каждый запрос обработку: если такой кейс случится, предлагать пользователю авторизоваться заново. В случае согласия - перекидывать на экран авторизации.

1. Договориться с @Mazian о специфическом коде ошибки в случае устаревшего кука (чтобы можно было однозначно определить источник ошибки)
2. Самое простое решение - кинуть по EventBus событие, что надо переавторизоваться, сбрасывать весь стек экранов и открывать экран логина

**Comment by kenrube** [comment]
Задачу можно временно отложить - есть целый год с момента релиза на ее реализацию

**Comment by Mazian** [comment]
#несрочно

;)

Отправлено со стеклышка, натертого спелыми яблоками.

**Comment by HombreTech** [comment]
526a3b444ec1c5a6ab765a3949a547417511db3e
