### ISSUE TITLE
Шаринг отзыва ведет не туда

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Android#95]
Пример: [Михаил Тырин "Желтая линия"](https://fantlab.ru/work42641), шаринг отзыва `gigrey` ведет на страницу `https://fantlab.ru/work127479#responses`, а должен вести на `https://fantlab.ru/work42641#response127479`

**Comment by HombreTech** [comment]
А теперь посмотри что будет, если отзыв находится не на первой странице. Думаешь я не рассматривал вариант перехода сразу к якорю нужного отзыва? :)

**Comment by kenrube** [comment]
Вроде норм (здесь следует учесть, что у меня в настройках стоит отображение всех отзывов за раз) :) [Такой](https://fantlab.ru/work1#response345184) переходит куда надо. В любом случае, ссылка совсем неправильная - ведет на левый ворк вместо нужного

**Comment by kenrube** [comment]
Пофиксил (простой вариант). Однако, остается вопрос с тем, что ссылка на отзывы, начиная со второй страницы ведет не туда куда следует. Универсально эту проблему не решить (хотя, казалось бы, можно просто добавить `?page={page}`), потому что количество отображаемых на странице отзывов каждый выбирает для себя сам (там много вариантов, от 15 до 2000 или вообще все за раз).

Также обязательно надо добавить в состав урла тип сортировки отзывов (`sort=${sort}`). По-умолчанию у юзера может стоять любой. В сочетании с пагинацией это может породить дикую путаницу.

**Comment by kenrube** [comment]
Добавил тип сортировки. Остается проблема с номером страницы. Я вижу 2 решения:
1. С сервера в каком-то запросе присылается значение настройки, сколько у юзера отзывов отображается за раз (и это значение может поменяться между заходами в приложение)
2. Фронт сам разруливает, на какую страницу перенаправить, если искомого отзыва нет на первой странице.

**Comment by kenrube** [comment]
Договорились с @Mazian, что он сделает [автоперенаправление к нужному отзыву](https://github.com/FantLab/FantLab-API/issues/36).

**Comment by HombreTech** [comment]
Отлично!

**Comment by kenrube** [comment]
Задача блокирована задачей https://github.com/FantLab/FantLab-API/issues/36

**Comment by kenrube** [comment]
Блокирующая задача сделана
